# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task_app', '0002_auto_20170907_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claims',
            options={'permissions': (('view_claims', 'Can see one or several claims.'), ('send_claims', 'Can send claim.'))},
        ),
        migrations.AlterModelOptions(
            name='worksheets',
            options={'permissions': (('view_worksheets', 'Can see one or several worksheets.'),)},
        ),
        migrations.AlterField(
            model_name='claims',
            name='sent_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
